"""Added Favorites model

Revision ID: 08fb9b343682
Revises: 15ca62f42901
Create Date: 2023-10-31 11:37:40.959154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fb9b343682'
down_revision = '15ca62f42901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('best_match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_match_id'], ['best_matches.id'], name=op.f('fk_favorites_best_match_id_best_matches')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    op.drop_table('favorites')
    # ### end Alembic commands ###
