"""update tables

Revision ID: 15ca62f42901
Revises: 040f0f4c070c
Create Date: 2023-10-27 10:18:05.923033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ca62f42901'
down_revision = '040f0f4c070c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_username', ['username'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
