"""added BM table

Revision ID: 69e523e12328
Revises: e77327959bcc
Create Date: 2023-11-06 15:48:50.551269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e523e12328'
down_revision = 'e77327959bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('astrological_sign_id', sa.Integer(), nullable=True),
    sa.Column('best_match_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['astrological_sign_id'], ['astrological_signs.id'], name=op.f('fk_best_matches_astrological_sign_id_astrological_signs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('best_matches')
    # ### end Alembic commands ###
