"""init

Revision ID: e77327959bcc
Revises: 
Create Date: 2023-11-06 15:30:24.437028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77327959bcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('astrological_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sign_name', sa.String(length=20), nullable=False),
    sa.Column('sign_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('astrological_sign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['astrological_sign_id'], ['astrological_signs.id'], name=op.f('fk_users_astrological_sign_id_astrological_signs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fav_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_user_id'], ['users.id'], name=op.f('fk_favorite_fav_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('users')
    op.drop_table('astrological_signs')
    # ### end Alembic commands ###
